### ISSUE TITLE
some question about the ablation study

### ISSUE THREAD

**Issue by RuiWang-coder** [lingyanruan/DRBNet#3]
Thanks for your excellent work! but i have a question about the ablation study: 
In table 6, your said "baseline is direct outputs the restored result without DRB", **i was wondering how does the baseline restored the image without DRB**? just concat the d and x in each scale?
Looking forward to your reply!

**Comment by lingyanruan** [comment]
Hi,

Sorry for the late reply.

The baseline model without DRB is an U-Net-like structure (the last layer has 3 channels).
