### ISSUE TITLE
About the dual pixel validation

### ISSUE THREAD

**Issue by c-yn** [lingyanruan/DRBNet#4]
Dear author, very much thanks for your excellent work.

I have some confusions about the dual pixel validation.  In your repo, you provide the configuration for dual pixel but no relevant performance report in the paper.  Regarding the dual pixel,  you use the R and L for the encoder-decoder stream, but for the other stream (downsampling the input to 1/8, 1/4...) you still use the C dataset. In this case, does it mean you use R, L and C for the dual pixel training?  However, IFANet only uses R and L datasets for the dual pixel training.

Thanks for your reply.

**Comment by lingyanruan** [comment]
Hi, 

Yes. For dual-pixel input, we use R, L, C for training as you described here. You could get C if you have R and L.

I think IFANet also use R, L, C for training (refer to their supplementary).
