### ISSUE TITLE
Web demo is down

### ISSUE THREAD

**Issue by sergiev** [lingyanruan/DRBNet#6]
When trying to inference succesfully uploaded image:
`NoServerFunctionError: No server function matching "process_img" has been registered`
When trying to inference image from examples:
`NoServerFunctionError: No server function matching "process_img_5" has been registered`
![image](https://user-images.githubusercontent.com/27900857/195643936-4c215816-00a8-42db-ade8-203339f4b523.png)

**Comment by lingyanruan** [comment]
Hi,

The web server will be off since it is expensive to keep, and the inference code has been released. But I reopen it and you could test it now.

Best
