### ISSUE TITLE
Questions about the pre-trained models.

### ISSUE THREAD

**Issue by C-water** [lingyanruan/DRBNet#7]
Hi,
I tested DRBNet on DPDD datasets using the provided wights (single and dual respectively).
For single 8bit input, the PSNR on DPDD is 24.94dB;
For single 16bit input, the PSNR on DPDD is 24.98dB;
For dual 8bit inputs, the PSNR on DPDD is 25.57dB;
For dual 16bit inputs, the PSNR on DPDD is 25.61dB;
The results seem to be inconsistent with those reported in the paper (25.725dB). How can I solve this problem?

Looking forward to your reply, thanks!

**Comment by lingyanruan** [comment]
Hi,

Did you exactly follow the instruction in this repository?
