### ISSUE TITLE
Some confusions about compution of Macs and Params

### ISSUE THREAD

**Issue by c-yn** [lingyanruan/DRBNet#8]
` Macs,params = get_model_complexity_info(network, (3, 720, 1280), as_strings=False)`
   `print('\t{:<30}  {:<8} B'.format('Computational complexity (Macs): ', Macs / 1000 ** 3 ))`

    print('\t{:<30}  {:<8} M'.format('Number of parameters: ',params / 1000 ** 2, '\n'))

Dear author, I found you computed Macs on 720\*1280 resolution. I wonder why you conduct operation '/1000 * 3' on Macs and '/1000*2' on params.

Thanks for your reply.

**Comment by lingyanruan** [comment]
Hi,

Sorry for the late reply.

These values are aligned with the unit of measurement utilized in this context, specifically using "B" for Macs. Consequently, we divide the original value by 1000^3 (or 1000 ** 3). Not (1000*3) as you mentioned. Same rule for params. 

Hope it helps.
